version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongo-local
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local
# Correr: docker compose up -d
# Detener: docker compose down
# URL: mongodb://admin:admin@localhost:27017
# URL MongoDB Compass: mongodb://admin:admin@localhost:27017/?authSource=admin
